List<Map<String, String>> countryList = [
  {"code": "ar", "name": "Argentina"},
  {"code": "au", "name": "Australia"},
  {"code": "at", "name": "Austria"},
  {"code": "be", "name": "Belgium"},
  {"code": "br", "name": "Brazil"},
  {"code": "bg", "name": "Bulgaria"},
  {"code": "ca", "name": "Canada"},
  {"code": "cn", "name": "China"},
  {"code": "co", "name": "Colombia"},
  {"code": "cz", "name": "Czech Republic"},
  {"code": "eg", "name": "Egypt"},
  {"code": "fr", "name": "France"},
  {"code": "de", "name": "Germany"},
  {"code": "gr", "name": "Greece"},
  {"code": "hk", "name": "Hong Kong"},
  {"code": "hu", "name": "Hungary"},
  {"code": "in", "name": "India"},
  {"code": "id", "name": "Indonesia"},
  {"code": "ie", "name": "Ireland"},
  {"code": "it", "name": "Italy"},
  {"code": "jp", "name": "Japan"},
  {"code": "lv", "name": "Latvia"},
  {"code": "lt", "name": "Lithuania"},
  {"code": "my", "name": "Malaysia"},
  {"code": "mx", "name": "Mexico"},
  {"code": "ma", "name": "Morocco"},
  {"code": "nl", "name": "Netherlands"},
  {"code": "nz", "name": "New Zealand"},
  {"code": "ng", "name": "Nigeria"},
  {"code": "no", "name": "Norway"},
  {"code": "ph", "name": "Philippines"},
  {"code": "pl", "name": "Poland"},
  {"code": "pt", "name": "Portugal"},
  {"code": "ro", "name": "Romania"},
  {"code": "sa", "name": "Saudi Arabia"},
  {"code": "rs", "name": "Serbia"},
  {"code": "sg", "name": "Singapore"},
  {"code": "sk", "name": "Slovakia"},
  {"code": "si", "name": "Slovenia"},
  {"code": "za", "name": "South Africa"},
  {"code": "kr", "name": "South Korea"},
  {"code": "se", "name": "Sweden"},
  {"code": "ch", "name": "Switzerland"},
  {"code": "tw", "name": "Taiwan"},
  {"code": "th", "name": "Thailand"},
  {"code": "tr", "name": "Turkey"},
  {"code": "ae", "name": "United Arab Emirates"},
  {"code": "ua", "name": "Ukraine"},
  {"code": "gb", "name": "United Kingdom"},
  {"code": "us", "name": "United States"},
  {"code": "ve", "name": "Venezuela"},
];
